### ISSUE TITLE
MANUAL-DEPLOYMENT.yml workflow_dispatch input conditionals are not working as excepted

### ISSUE THREAD

**Issue by u-ways** [propactive/propactive#48]
It seems that the latest manual deployment trigger did not take into account that the input was for Gradle Plugin Portal release only. Therefore, it also tried to deployed to Maven Central. See:

https://github.com/propactive/propactive/actions/runs/3380968633

**Comment by u-ways** [comment]
It seems that `workflow_dispatch` conditionals were using the incorrect syntax to evaluate input events. This has been changed from:

```yaml
      - name: 'Publishing to maven central'
        if: ${{ inputs.deployment == 'propactive-jvm (Maven Central Repository)' }} || ${{ inputs.deployment == 'all' }}
        run: make publish-propactive-jvm-jars
      - name: 'Publishing to gradle plugin'
        if: ${{ inputs.deployment == 'propactive-plugin (Gradle Plugin Portal)' }} || ${{ inputs.deployment == 'all' }}
        run: make publish-propactive-plugin-jars
```

To:

```yaml
      - name: 'Publishing to maven central'
        if: (inputs.deployment == 'propactive-jvm (Maven Central Repository)' || inputs.deployment == 'all')
        run: make publish-propactive-jvm-jars
      - name: 'Publishing to gradle plugin'
        if: (inputs.deployment == 'propactive-plugin (Gradle Plugin Portal)'  || inputs.deployment == 'all')
        run: make publish-propactive-plugin-jars
```
